---
networks:
  ha_net:
    driver: bridge
    name: ha_net

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:${HA_VERSION}
    container_name: ${HA_CONTAINER_NAME:-homeassistant}
    # network_mode: host
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro   # Optional: Bluetooth
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - "${HA_PORT:-8123}:8123"
    networks:
      - ha_net

  # python-matter-server
  matter-server:
    image: ghcr.io/matter-js/python-matter-server:stable
    container_name: ${MS_CONTAINER_NAME:-matter-server}
    restart: unless-stopped
    # Required for mDNS to work correctly
    # network_mode: host
    #security_opt:
    #  # Needed for Bluetooth via dbus
    #  - apparmor:unconfined
    volumes:
      # Create an .env file that sets the USERDIR environment variable.
      - ${MS_DATA_DIR:-$HOME}/srv/matter-server/data:/data/
      # Required for Bluetooth via D-Bus
      # - /run/dbus:/run/dbus:ro
    # If you adjust command line, make sure to pass the default CMD arguments too:
    #command: --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0
    networks:
      - ha_net


#  matter-server:
#    image: ghcr.io/home-assistant-libs/python-matter-server:stable
#    network_mode: host
#    restart: unless-stopped
#
  mariadb:
    image: mariadb:11
    container_name: ${MARIADB_CONTAINER_NAME:-mariadb}
    restart: unless-stopped
    #ports:
    #  - "3306:3306"
    environment:
      - MARIADB_DATABASE=homeassistant
      - MARIADB_USER=ha
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ${MARIADB_DIR}:/var/lib/mysql
    command: >
      --innodb_buffer_pool_size=256M
      --innodb_flush_log_at_trx_commit=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "ha", "-p${DB_PASSWORD}"]
      interval: 20s
      timeout: 5s
      retries: 10
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    networks:
      - ha_net
